version: '2'
services:
    assistance-app:
        image: assistance
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://assistance-postgresql:5432/assistance
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=assistance-elasticsearch:9300
        ports:
            - 8080:8080
    assistance-postgresql:
        extends:
            file: postgresql.yml
            service: assistance-postgresql
    assistance-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: assistance-elasticsearch
